########### Arquivo contendo todas as keys dos botões e seus devidos textos ##########

### MENU SCREEN!

X1_COORDINATES_BUTTON_TEXT     = 'X'
X1_COORDINATES_BUTTON_KEY      = '-X1_COORDINATES_BUTTON-'

Y1_COORDINATES_BUTTON_TEXT     = 'Y'
Y1_COORDINATES_BUTTON_KEY      = '-Y1_COORDINATES_BUTTON-'

MENU_GRAPH_TEXT                = 'CANVAS'
MENU_GRAPH_KEY                 = '-CANVAS-'

MENU_DRAW_PIXEL_TEXT           = 'Desenhar Pixel'
MENU_DRAW_PIXEL_KEY            = '-MENU_DRAW_PIXEL-'

MENU_SELECT_COLOR_TEXT         = 'Selecionar Cor'
MENU_SELECT_COLOR_KEY          = '-MENU_SELECT_COLOR-'

MENU_CLOSE_TEXT                = 'Sair'
MENU_CLOSE_KEY                 = '-MENU_CLOSE-'

MENU_ERASE_TEXT                = 'Selecionar Borracha'
MENU_ERASE_KEY                 = '-ERASE_KEY-'

MENU_ERASE_ALL_TEXT            = 'Apagar Tudo'
MENU_ERASE_ALL_KEY             = '-MENU_ERASE_ALL_KEY-'

MENU_APPLY_CLIPPING_TEXT       = 'Aplicar Recorte'
MENU_APPLY_CLIPPING_KEY        = '-MENU_APPLY_CLIPPING_KEY-'

MENU_APPLY_FILL_TEXT           = 'Aplicar Preenchimento'
MENU_APPLY_FILL_KEY            = '-MENU_APPLY_FILL_KEY-'

MENU_APPLY_TRANSFORMATION_TEXT = 'Aplicar Transformação'
MENU_APPLY_TRANSFORMATION_KEY  = '-MENU_APPLY_TRANSFORMATION_KEY-'

MENU_ERASER_SIZE_SLIDER_TEXT   = 'Tamanho da Borracha'
MENU_ERASER_SIZE_SLIDER_KEY    = '-MENU_ERASER_SIDE_SLIDER_KEY-'

MENU_DRAW_CIRCLE_TEXT          = 'Desenhar Círculo'
MENU_DRAW_CIRCLE_KEY           = '-MENU_DRAW_CIRCLE_KEY-'

MENU_CIRCLE_RADIUS_TEXT        = 'Raio do Círculo'
MENU_CIRCLE_RADIUS_KEY         = '-MENU_CIRCLE_RADIUS_KEY-'

MENU_CIRCLE_NPOINTS_TEXT       = 'Resolução do Círculo'
MENU_CIRCLE_NPOINTS_KEY        = '-MENU_CIRCLE_NPOINTS_KEY-'

# CHOOSE_COLOR.PY SCREEN!
CHOOSE_COLOR_APPLY_TEXT        = 'Aplicar Cor'
CHOOSE_COLOR_APPLY_KEY         = '-SELECT_COLOR_APPLY-'

CHOOSE_COLOR_RED_SLIDER_TEXT   = 'Intensidade Vermelho'
CHOOSE_COLOR_RED_SLIDER_KEY    = '-CHOOSE_COLOR_RED_SLIDER_KEY-'
CHOOSE_COLOR_GREEN_SLIDER_TEXT = 'Intensidade Verde'
CHOOSE_COLOR_GREEN_SLIDER_KEY  = '-CHOOSE_COLOR_GREEN_SLIDER_KEY-'
CHOOSE_COLOR_BLUE_SLIDER_TEXT  = 'Intensidade Azul'
CHOOSE_COLOR_BLUE_SLIDER_KEY   = '-CHOOSE_COLOR_BLUE_SLIDER_KEY-'

CHOOSE_COLOR_GRAPH_KEY         = '-CHOOSE_COLOR_GRAPH_KEY-'


# CHOOSE_TRANSFORMATION.PY SCREEN!

CHOOSE_TRANSFORMATION_APPLY_TEXT = 'Aplicar Transformação'
CHOOSE_TRANSFORMATION_APPLY_KEY  = '-CHOOSE_TRANSFORMATION_APPLY_KEY-'

CHOOSE_TRANSFORMATION_OPTION_DEFAULT_TRANSFORMATION         = 'Translação'
CHOOSE_TRANSFORMATION_OPTION_CHOSEN_TRANSFORMATION_KEY      = '-CHOOSE_TRANSFORMATION_OPTION_CHOSEN_TRANSFORMATION_KEY-'

CHOOSE_TRANSFORMATION_OPTION_DEFAULT_AXIS                   = 'Ambos'
CHOOSE_TRANSFORMATION_OPTION_CHOSEN_AXIS_KEY                = '-CHOOSE_TRANSFORMATION_OPTION_CHOSEN_AXIS_KEY-'

CHOOSE_TRANSFORMATION_OPTION_DEFAULT_FACTOR                 = 2
CHOOSE_TRANSFORMATION_OPTION_CHOSEN_FACTOR_KEY              = '-CHOOSE_TRANSFORMATION_OPTION_CHOSEN_FACTOR_KEY-'

CHOOSE_TRANSFORMATION_OPTION_DEFAULT_ROTATION_ANGLE         = 90
CHOOSE_TRANSFORMATION_OPTION_CHOSEN_ROTATION_ANGLE_KEY      = '-CHOOSE_TRANSFORMATION_OPTION_CHOSEN_ROTATION_ANGLE_KEY-'

CHOOSE_TRANSFORMATION_OPTION_DEFAULT_ROTATION_DIRECTION     = 'Horário'
CHOOSE_TRANSFORMATION_OPTION_CHOSEN_ROTATION_DIRECTION_KEY  = '-CHOOSE_TRANSFORMATION_OPTION_CHOSEN_ROTATION_DIRECTION_KEY-'

# CHOOSE ALGORITHMS
CHOOSE_LINE_ALGORITHM_DROPDOWN_TEXT     = 'Selecionar Algoritmo de Linha'

CHOOSE_LINE_ALGORITHM_DEFAULT_OPTION    = 'Padrão'
CHOOSE_LINE_ALGORITHM_CHOICE_1          = 'Padrão'
CHOOSE_LINE_ALGORITHM_CHOICE_2          = 'DDA'
CHOOSE_LINE_ALGORITHM_CHOICE_3          = 'Bresenham'

CHOOSE_LINE_ALGORITHM_CHOSEN_OPTION_KEY = '-CHOOSE_LINE_ALGORITHM_DEFAULT_OPTION_KEY-'
CHOOSE_LINE_ALGORITHM_APPLY_KEY         = '-CHOOSE_LINE_ALGORITHM_APPLY_KEY-'


# CLIPPING ALGORITHMS

CHOOSE_CLIPPING_ALGORITHM_DROPDOWN_TEXT     = 'Selecionar Algoritmo de Recorte'
   
CHOOSE_CLIPPING_ALGORITHM_DEFAULT_OPTION    = 'Cohen-Sutherland'
CHOOSE_CLIPPING_ALGORITHM_CHOICE_1          = 'Cohen-Sutherland'
CHOOSE_CLIPPING_ALGORITHM_CHOICE_2          = 'Liang-Barsky'

CHOOSE_CLIPPING_ALGORITHM_CHOSEN_OPTION_KEY = '-CHOOSE_CLIPPING_ALGORITHM_DEFAULT_OPTION_KEY-'
CHOOSE_CLIPPING_ALGORITHM_APPLY_KEY         = '-CHOOSE_CLIPPING_ALGORITHM_APPLY_KEY-'

MAX_X_VALUE_CLIPPING_TEXT = 'X máximo para recorte'
MIN_X_VALUE_CLIPPING_TEXT = 'X mínimo para recorte'
MAX_Y_VALUE_CLIPPING_TEXT = 'Y máximo para recorte'
MIN_Y_VALUE_CLIPPING_TEXT = 'Y mínimo para recorte'
MAX_X_VALUE_CLIPPING_KEY  = '-MAX_X_VALUE_CLIPPING_KEY-'
MIN_X_VALUE_CLIPPING_KEY  = '-MIN_X_VALUE_CLIPPING_KEY-'
MAX_Y_VALUE_CLIPPING_KEY  = '-MAX_Y_VALUE_CLIPPING_KEY-'
MIN_Y_VALUE_CLIPPING_KEY  = '-MIN_Y_VALUE_CLIPPING_KEY-'

# FILL ALGORITHMS

CHOOSE_FILL_ALGORITHM_DROPDOWN_TEXT     = 'Selecionar Algoritmo de Preenchimento'

CHOOSE_FILL_ALGORITHM_DEFAULT_OPTION    = 'Boundary Fill'
CHOOSE_FILL_ALGORITHM_CHOICE_1          = 'Boundary Fill'
CHOOSE_FILL_ALGORITHM_CHOICE_2          = 'Flood Fill'

CHOOSE_FILL_ALGORITHM_CHOSEN_OPTION_KEY = '-CHOOSE_FILL_ALGORITHM_DEFAULT_OPTION_KEY-'
CHOOSE_FILL_ALGORITHM_APPLY_KEY         = '-CHOOSE_FILL_ALGORITHM_APPLY_KEY-'