########### Arquivo contendo todas as keys dos botões e seus devidos textos ##########

### Menu principal

X1_COORDINATES_BUTTON_TEXT = 'X1'
X1_COORDINATES_BUTTON_KEY  = '-X1_COORDINATES_BUTTON-'

Y1_COORDINATES_BUTTON_TEXT = 'Y1'
Y1_COORDINATES_BUTTON_KEY  = '-Y1_COORDINATES_BUTTON-'

X2_COORDINATES_BUTTON_TEXT = 'X2'
X2_COORDINATES_BUTTON_KEY  = '-X2_COORDINATES_BUTTON-'

Y2_COORDINATES_BUTTON_TEXT = 'Y2'
Y2_COORDINATES_BUTTON_KEY  = '-Y2_COORDINATES_BUTTON-'

GUI_GRAPH_TEXT          = 'CANVAS'
GUI_GRAPH_KEY           = '-CANVAS-'

GUI_DRAW_PIXEL_TEXT     = 'Desenhar Pixel'
GUI_DRAW_PIXEL_KEY      = '-GUI_DRAW_PIXEL-'

GUI_SELECT_COLOR_TEXT   = 'Selecionar Cor'
GUI_SELECT_COLOR_KEY    = '-GUI_SELECT_COLOR-'

GUI_CLOSE_TEXT          = 'Sair'
GUI_CLOSE_KEY           = '-GUI_CLOSE-'